// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class agenda_status
{
    public Guid agenda_status_id { get; set; }

    public string agenda_status_name { get; set; }

    public string created_by { get; set; }

    public DateTime? created_date { get; set; }

    public string updated_by { get; set; }

    public DateTime? updated_date { get; set; }

    public virtual ICollection<leave_request> leave_request { get; set; } = new List<leave_request>();
}