// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class chapter
{
    public Guid chapter_id { get; set; }

    public Guid course_id { get; set; }

    public string chapter_title { get; set; }

    public string created_by { get; set; }

    public DateTime? created_date { get; set; }

    public string updated_by { get; set; }

    public DateTime? updated_date { get; set; }

    public virtual ICollection<chapter_content> chapter_content { get; set; } = new List<chapter_content>();

    public virtual course course { get; set; }
}