// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class chapter_content
{
    public Guid content_id { get; set; }

    public Guid chapter_id { get; set; }

    public string content_title { get; set; }

    public string content_body { get; set; }

    public string created_by { get; set; }

    public DateTime? created_date { get; set; }

    public string updated_by { get; set; }

    public DateTime? updated_date { get; set; }

    public virtual chapter chapter { get; set; }

    public virtual ICollection<user_progress> user_progress { get; set; } = new List<user_progress>();
}