// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class check_in_out
{
    public Guid check_inout_id { get; set; }

    public Guid user_id { get; set; }

    public DateTime? check_in { get; set; }

    public DateTime? check_out { get; set; }

    public DateTime? check_dates { get; set; }

    public string created_by { get; set; }

    public DateTime created_date { get; set; }

    public string updated_by { get; set; }

    public DateTime? updated_date { get; set; }

    public virtual user user { get; set; }

    public virtual ICollection<user_agenda> user_agenda { get; set; } = new List<user_agenda>();
}