// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class course
{
    public Guid course_id { get; set; }

    public string course_name { get; set; }

    public string subtitle { get; set; }

    public string description { get; set; }

    public DateOnly start_date { get; set; }

    public DateOnly end_date { get; set; }

    public TimeOnly start_time { get; set; }

    public TimeOnly end_time { get; set; }

    public string created_by { get; set; }

    public DateTime? created_date { get; set; }

    public string updated_by { get; set; }

    public DateTime? updated_date { get; set; }

    public virtual ICollection<chapter> chapter { get; set; } = new List<chapter>();

    public virtual ICollection<course_complete> course_complete { get; set; } = new List<course_complete>();

    public virtual ICollection<question> question { get; set; } = new List<question>();

    public virtual ICollection<registration> registration { get; set; } = new List<registration>();

    public virtual ICollection<user_progress> user_progress { get; set; } = new List<user_progress>();

    public virtual ICollection<user_question> user_question { get; set; } = new List<user_question>();

    public virtual ICollection<user_result> user_result { get; set; } = new List<user_result>();
}