// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Ems.Data.Entities;

public partial class EmsContext : DbContext
{
    public EmsContext(DbContextOptions<EmsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<agenda_status> agenda_status { get; set; }

    public virtual DbSet<chapter> chapter { get; set; }

    public virtual DbSet<chapter_content> chapter_content { get; set; }

    public virtual DbSet<check_in_out> check_in_out { get; set; }

    public virtual DbSet<checking_status> checking_status { get; set; }

    public virtual DbSet<course> course { get; set; }

    public virtual DbSet<course_complete> course_complete { get; set; }

    public virtual DbSet<leave_half> leave_half { get; set; }

    public virtual DbSet<leave_request> leave_request { get; set; }

    public virtual DbSet<leave_request_status> leave_request_status { get; set; }

    public virtual DbSet<menu> menu { get; set; }

    public virtual DbSet<menu_role> menu_role { get; set; }

    public virtual DbSet<option> option { get; set; }

    public virtual DbSet<position> position { get; set; }

    public virtual DbSet<question> question { get; set; }

    public virtual DbSet<registration> registration { get; set; }

    public virtual DbSet<role> role { get; set; }

    public virtual DbSet<status> status { get; set; }

    public virtual DbSet<user> user { get; set; }

    public virtual DbSet<user_agenda> user_agenda { get; set; }

    public virtual DbSet<user_progress> user_progress { get; set; }

    public virtual DbSet<user_question> user_question { get; set; }

    public virtual DbSet<user_result> user_result { get; set; }

    public virtual DbSet<user_role> user_role { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresEnum("lang", new[] { "th", "en" })
            .HasPostgresExtension("uuid-ossp");

        modelBuilder.Entity<agenda_status>(entity =>
        {
            entity.HasKey(e => e.agenda_status_id).HasName("agenda_status_pkey");

            entity.ToTable("agenda_status", "ems");

            entity.Property(e => e.agenda_status_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.agenda_status_name).HasMaxLength(16);
            entity.Property(e => e.created_by)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.updated_by)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
        });

        modelBuilder.Entity<chapter>(entity =>
        {
            entity.HasKey(e => e.chapter_id).HasName("chapter_pkey");

            entity.ToTable("chapter", "ems");

            entity.Property(e => e.chapter_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.chapter_title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.course).WithMany(p => p.chapter)
                .HasForeignKey(d => d.course_id)
                .HasConstraintName("fk_course");
        });

        modelBuilder.Entity<chapter_content>(entity =>
        {
            entity.HasKey(e => e.chapter_content_id).HasName("chapter_content_pkey");

            entity.ToTable("chapter_content", "ems");

            entity.Property(e => e.chapter_content_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.content_body).IsRequired();
            entity.Property(e => e.content_title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.chapter).WithMany(p => p.chapter_content)
                .HasForeignKey(d => d.chapter_id)
                .HasConstraintName("fk_chapter");
        });

        modelBuilder.Entity<check_in_out>(entity =>
        {
            entity.HasKey(e => e.check_inout_id).HasName("check_in_out_pkey");

            entity.ToTable("check_in_out", "ems");

            entity.Property(e => e.check_inout_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.check_dates).HasDefaultValueSql("CURRENT_TIMESTAMP");
            entity.Property(e => e.check_in).HasMaxLength(100);
            entity.Property(e => e.check_out).HasMaxLength(100);
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.checking_status).WithMany(p => p.check_in_out)
                .HasForeignKey(d => d.checking_status_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_checking_status_id");

            entity.HasOne(d => d.leave_request).WithMany(p => p.check_in_out)
                .HasForeignKey(d => d.leave_request_id)
                .HasConstraintName("fk_leave_request_id");

            entity.HasOne(d => d.user).WithMany(p => p.check_in_out)
                .HasForeignKey(d => d.user_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_user_id");
        });

        modelBuilder.Entity<checking_status>(entity =>
        {
            entity.HasKey(e => e.checking_status_id).HasName("checking_status_pkey");

            entity.ToTable("checking_status", "ems");

            entity.Property(e => e.checking_status_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.checking_status_name).HasMaxLength(100);
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
        });

        modelBuilder.Entity<course>(entity =>
        {
            entity.HasKey(e => e.course_id).HasName("course_pkey");

            entity.ToTable("course", "ems");

            entity.Property(e => e.course_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.course_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.subtitle)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
        });

        modelBuilder.Entity<course_complete>(entity =>
        {
            entity.HasKey(e => e.course_complete_id).HasName("coursecomplate_pkey");

            entity.ToTable("course_complete", "ems");

            entity.Property(e => e.course_complete_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.course).WithMany(p => p.course_complete)
                .HasForeignKey(d => d.course_id)
                .HasConstraintName("fk_coursecomplete_course");

            entity.HasOne(d => d.status).WithMany(p => p.course_complete)
                .HasForeignKey(d => d.status_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_coursecomplete_status");

            entity.HasOne(d => d.user).WithMany(p => p.course_complete)
                .HasForeignKey(d => d.user_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_coursecomplete_user");
        });

        modelBuilder.Entity<leave_half>(entity =>
        {
            entity.HasKey(e => e.leave_half_id).HasName("leave_half_pkey");

            entity.ToTable("leave_half", "ems");

            entity.Property(e => e.leave_half_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.leave_type_name).HasMaxLength(50);
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
        });

        modelBuilder.Entity<leave_request>(entity =>
        {
            entity.HasKey(e => e.leave_request_id).HasName("leave_request_pkey");

            entity.ToTable("leave_request", "ems");

            entity.Property(e => e.leave_request_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.admin_message).HasMaxLength(100);
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.leave_request_date).HasMaxLength(100);
            entity.Property(e => e.leave_request_description).HasMaxLength(100);
            entity.Property(e => e.status_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.agenda_status).WithMany(p => p.leave_request)
                .HasForeignKey(d => d.agenda_status_id)
                .HasConstraintName("fk_agenda_status");

            entity.HasOne(d => d.leave_half).WithMany(p => p.leave_request)
                .HasForeignKey(d => d.leave_half_id)
                .HasConstraintName("fk_leave_half_id");

            entity.HasOne(d => d.leave_request_status).WithMany(p => p.leave_request)
                .HasForeignKey(d => d.leave_request_status_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_leave_request_status_id");

            entity.HasOne(d => d.user).WithMany(p => p.leave_request)
                .HasForeignKey(d => d.user_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_user_id");
        });

        modelBuilder.Entity<leave_request_status>(entity =>
        {
            entity.HasKey(e => e.leave_request_status_id).HasName("leave_request_status_pkey");

            entity.ToTable("leave_request_status", "ems");

            entity.Property(e => e.leave_request_status_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.leave_request_status_name).HasMaxLength(100);
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
        });

        modelBuilder.Entity<menu>(entity =>
        {
            entity.HasKey(e => e.menu_id).HasName("menu_pk");

            entity.ToTable("menu", "ems");

            entity.Property(e => e.menu_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date).HasColumnType("timestamp without time zone");
            entity.Property(e => e.menu_code).HasMaxLength(10);
            entity.Property(e => e.menu_icon).HasMaxLength(100);
            entity.Property(e => e.menu_name).HasMaxLength(100);
            entity.Property(e => e.menu_path).HasMaxLength(100);
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date).HasColumnType("timestamp without time zone");
        });

        modelBuilder.Entity<menu_role>(entity =>
        {
            entity.HasKey(e => e.menu_role_id).HasName("menu_role_pk");

            entity.ToTable("menu_role", "ems");

            entity.Property(e => e.menu_role_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.created_date).HasColumnType("timestamp without time zone");
            entity.Property(e => e.updated_by)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.updated_date).HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.menu).WithMany(p => p.menu_role)
                .HasForeignKey(d => d.menu_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("menu_role_menu_fk");

            entity.HasOne(d => d.role).WithMany(p => p.menu_role)
                .HasForeignKey(d => d.role_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("menu_role_role_fk");
        });

        modelBuilder.Entity<option>(entity =>
        {
            entity.HasKey(e => e.option_id).HasName("option_pkey");

            entity.ToTable("option", "ems");

            entity.Property(e => e.option_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.is_correct).HasDefaultValue(false);
            entity.Property(e => e.option_text).IsRequired();
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.question).WithMany(p => p.option)
                .HasForeignKey(d => d.question_id)
                .HasConstraintName("fk_option_question");
        });

        modelBuilder.Entity<position>(entity =>
        {
            entity.HasKey(e => e.position_id).HasName("positions_pkey");

            entity.ToTable("position", "ems");

            entity.Property(e => e.position_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.position_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
        });

        modelBuilder.Entity<question>(entity =>
        {
            entity.HasKey(e => e.question_id).HasName("question_pkey");

            entity.ToTable("question", "ems");

            entity.Property(e => e.question_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.question_text).IsRequired();
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.course).WithMany(p => p.question)
                .HasForeignKey(d => d.course_id)
                .HasConstraintName("fk_question_course");
        });

        modelBuilder.Entity<registration>(entity =>
        {
            entity.HasKey(e => e.registration_id).HasName("registration_pkey");

            entity.ToTable("registration", "ems");

            entity.Property(e => e.registration_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.course).WithMany(p => p.registration)
                .HasForeignKey(d => d.course_id)
                .HasConstraintName("fk_course");

            entity.HasOne(d => d.status).WithMany(p => p.registration)
                .HasForeignKey(d => d.status_id)
                .HasConstraintName("fk_status");

            entity.HasOne(d => d.user).WithMany(p => p.registration)
                .HasForeignKey(d => d.user_id)
                .HasConstraintName("fk_user");
        });

        modelBuilder.Entity<role>(entity =>
        {
            entity.HasKey(e => e.role_id).HasName("role_pkey");

            entity.ToTable("role", "ems");

            entity.Property(e => e.role_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.role_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
        });

        modelBuilder.Entity<status>(entity =>
        {
            entity.HasKey(e => e.status_id).HasName("status_pkey");

            entity.ToTable("status", "ems");

            entity.HasIndex(e => e.status_name, "status_status_name_key").IsUnique();

            entity.Property(e => e.status_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.status_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
        });

        modelBuilder.Entity<user>(entity =>
        {
            entity.HasKey(e => e.user_id).HasName("user_pkey");

            entity.ToTable("user", "ems");

            entity.HasIndex(e => e.email, "user_email_key").IsUnique();

            entity.Property(e => e.user_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.first_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.last_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.phone)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.position).WithMany(p => p.user)
                .HasForeignKey(d => d.position_id)
                .HasConstraintName("fk_user_position");
        });

        modelBuilder.Entity<user_agenda>(entity =>
        {
            entity.HasKey(e => e.users_ag_id).HasName("user_agenda_pkey");

            entity.ToTable("user_agenda", "ems");

            entity.Property(e => e.users_ag_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.updated_by)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.user_id).HasDefaultValueSql("uuid_generate_v4()");

            entity.HasOne(d => d.check_inout).WithMany(p => p.user_agenda)
                .HasForeignKey(d => d.check_inout_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_check_inout_id");

            entity.HasOne(d => d.user).WithMany(p => p.user_agenda)
                .HasForeignKey(d => d.user_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("user_agenda_user_id_fkey");
        });

        modelBuilder.Entity<user_progress>(entity =>
        {
            entity.HasKey(e => e.user_progress_id).HasName("user_progress_pkey");

            entity.ToTable("user_progress", "ems");

            entity.Property(e => e.user_progress_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.record_read).HasDefaultValue(false);
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.chapter_content).WithMany(p => p.user_progress)
                .HasForeignKey(d => d.chapter_content_id)
                .HasConstraintName("fk_content");

            entity.HasOne(d => d.chapter).WithMany(p => p.user_progress)
                .HasForeignKey(d => d.chapter_id)
                .HasConstraintName("fk_chapter");

            entity.HasOne(d => d.course).WithMany(p => p.user_progress)
                .HasForeignKey(d => d.course_id)
                .HasConstraintName("fk_course");

            entity.HasOne(d => d.user).WithMany(p => p.user_progress)
                .HasForeignKey(d => d.user_id)
                .HasConstraintName("fk_user");
        });

        modelBuilder.Entity<user_question>(entity =>
        {
            entity.HasKey(e => e.user_question_id).HasName("user_question_pkey");

            entity.ToTable("user_question", "ems");

            entity.Property(e => e.user_question_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.course).WithMany(p => p.user_question)
                .HasForeignKey(d => d.course_id)
                .HasConstraintName("fk_user_question_course");

            entity.HasOne(d => d.option).WithMany(p => p.user_question)
                .HasForeignKey(d => d.option_id)
                .HasConstraintName("fk_user_question_option");

            entity.HasOne(d => d.question).WithMany(p => p.user_question)
                .HasForeignKey(d => d.question_id)
                .HasConstraintName("fk_user_question_question");

            entity.HasOne(d => d.user).WithMany(p => p.user_question)
                .HasForeignKey(d => d.user_id)
                .HasConstraintName("fk_user_question_user");
        });

        modelBuilder.Entity<user_result>(entity =>
        {
            entity.HasKey(e => e.result_id).HasName("user_result_pkey");

            entity.ToTable("user_result", "ems");

            entity.Property(e => e.result_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.course).WithMany(p => p.user_result)
                .HasForeignKey(d => d.course_id)
                .HasConstraintName("fk_user_result_course");

            entity.HasOne(d => d.user).WithMany(p => p.user_result)
                .HasForeignKey(d => d.user_id)
                .HasConstraintName("fk_user_result_user");
        });

        modelBuilder.Entity<user_role>(entity =>
        {
            entity.HasKey(e => e.user_role_id).HasName("user_role_pkey");

            entity.ToTable("user_role", "ems");

            entity.Property(e => e.user_role_id).HasDefaultValueSql("uuid_generate_v4()");
            entity.Property(e => e.created_by).HasMaxLength(100);
            entity.Property(e => e.created_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");
            entity.Property(e => e.updated_by).HasMaxLength(100);
            entity.Property(e => e.updated_date)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone");

            entity.HasOne(d => d.role).WithMany(p => p.user_role)
                .HasForeignKey(d => d.role_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_role");

            entity.HasOne(d => d.user).WithMany(p => p.user_role)
                .HasForeignKey(d => d.user_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_user_role");
        });
        modelBuilder.HasSequence("db_district_district_code_seq");
        modelBuilder.HasSequence("db_district_district_id_seq");
        modelBuilder.HasSequence("db_postal_code_postal_code_id_seq").HasMax(2147483647L);
        modelBuilder.HasSequence("db_province_province_code_seq");
        modelBuilder.HasSequence("db_province_province_id_seq");
        modelBuilder.HasSequence("db_subdistrict_subdistrict_code_seq");
        modelBuilder.HasSequence("db_subdistrict_subdistrict_id_seq");
        modelBuilder.HasSequence("history_id_seq");
        modelBuilder.HasSequence("pm_backlog_backlog_id_seq");
        modelBuilder.HasSequence("pm_customer_customer_id_seq");
        modelBuilder.HasSequence("pm_project_member_project_member_id_seq");
        modelBuilder.HasSequence("pm_project_project_id_seq");
        modelBuilder.HasSequence("pm_roadmap_roadmap_id_seq");
        modelBuilder.HasSequence("seq");
        modelBuilder.HasSequence("su_user_user_id_seq");
        modelBuilder.HasSequence("tw_customer_customer_id_seq");
        modelBuilder.HasSequence("tw_project_project_id_seq");
        modelBuilder.HasSequence("tw_task_work_task_work_id_seq");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}