// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class leave_request
{
    public Guid leave_request_id { get; set; }

    public Guid user_id { get; set; }

    public Guid leave_request_status_id { get; set; }

    public string leave_request_date { get; set; }

    public string leave_request_description { get; set; }

    public string status_name { get; set; }

    public string created_by { get; set; }

    public DateTime? created_date { get; set; }

    public string updated_by { get; set; }

    public DateTime? updated_date { get; set; }

    public Guid? leave_half_id { get; set; }

    public string leave_start_time { get; set; }

    public string leave_end_time { get; set; }

    public virtual ICollection<check_in_out> check_in_out { get; set; } = new List<check_in_out>();

    public virtual leave_half leave_half { get; set; }

    public virtual leave_request_status leave_request_status { get; set; }

    public virtual user user { get; set; }
}