// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class leave_half
{
    public Guid leave_half_id { get; set; }

    public string leave_type_name { get; set; }

    public virtual ICollection<leave_request> leave_request { get; set; } = new List<leave_request>();
}