// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class leave_request
{
    public Guid lreq_id { get; set; }

    public Guid user_id { get; set; }

    public DateOnly lreq_date { get; set; }

    public string lreq_description { get; set; }

    public string create_by { get; set; }

    public DateTime create_date { get; set; }

    public string update_by { get; set; }

    public DateTime update_date { get; set; }

    public virtual user user { get; set; }

    public virtual ICollection<user_agenda> user_agenda { get; set; } = new List<user_agenda>();
}