// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class menu
{
    public Guid menu_id { get; set; }

    public Guid? menu_parent_id { get; set; }

    public string menu_code { get; set; }

    public string menu_name { get; set; }

    public string menu_icon { get; set; }

    public string menu_path { get; set; }

    public bool? is_menu_parent { get; set; }

    public bool? active { get; set; }

    public string created_by { get; set; }

    public DateTime? created_date { get; set; }

    public string updated_by { get; set; }

    public DateTime? updated_date { get; set; }

    public virtual ICollection<menu_role> menu_role { get; set; } = new List<menu_role>();
}