// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class option
{
    public Guid option_id { get; set; }

    public Guid question_id { get; set; }

    public string option_text { get; set; }

    public bool? is_correct { get; set; }

    public string created_by { get; set; }

    public DateTime? created_date { get; set; }

    public string updated_by { get; set; }

    public DateTime? updated_date { get; set; }

    public virtual question question { get; set; }

    public virtual ICollection<user_question> user_question { get; set; } = new List<user_question>();
}