// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class status
{
    public Guid status_id { get; set; }

    public string status_name { get; set; }

    public string created_by { get; set; }

    public DateTime? created_date { get; set; }

    public string updated_by { get; set; }

    public DateTime? updated_date { get; set; }

    public virtual ICollection<course_complete> course_complete { get; set; } = new List<course_complete>();

    public virtual ICollection<registration> registration { get; set; } = new List<registration>();
}