// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class user
{
    public Guid user_id { get; set; }

    public string first_name { get; set; }

    public string last_name { get; set; }

    public string email { get; set; }

    public string password { get; set; }

    public string phone { get; set; }

    public Guid? position_id { get; set; }

    public string created_by { get; set; }

    public DateTime? created_date { get; set; }

    public string updated_by { get; set; }

    public DateTime? updated_date { get; set; }

    public virtual ICollection<check_in_out> check_in_out { get; set; } = new List<check_in_out>();

    public virtual ICollection<leave_request> leave_request { get; set; } = new List<leave_request>();

    public virtual position position { get; set; }

    public virtual ICollection<registration> registration { get; set; } = new List<registration>();

    public virtual ICollection<user_agenda> user_agenda { get; set; } = new List<user_agenda>();

    public virtual ICollection<user_progress> user_progress { get; set; } = new List<user_progress>();

    public virtual ICollection<user_question> user_question { get; set; } = new List<user_question>();
}