// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class user_role
{
    public Guid user_role_id { get; set; }

    public Guid user_id { get; set; }

    public Guid role_id { get; set; }

    public string created_by { get; set; }

    public DateTime? created_date { get; set; }

    public string updated_by { get; set; }

    public DateTime? updated_date { get; set; }

    public virtual role role { get; set; }

    public virtual user user { get; set; }
}