// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class user_agenda
{
    public Guid users_ag_id { get; set; }

    public Guid user_id { get; set; }

    public Guid check_inout_id { get; set; }

    public Guid? lreq_id { get; set; }

    public string created_by { get; set; }

    public DateTime created_date { get; set; }

    public string updated_by { get; set; }

    public DateTime updated_date { get; set; }

    public virtual check_in_out check_inout { get; set; }

    public virtual user user { get; set; }
}