// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class user_question
{
    public Guid user_question_id { get; set; }

    public Guid user_id { get; set; }

    public Guid course_id { get; set; }

    public Guid question_id { get; set; }

    public Guid option_id { get; set; }

    public int? score { get; set; }

    public bool? pass_status { get; set; }

    public string created_by { get; set; }

    public DateTime? created_date { get; set; }

    public string updated_by { get; set; }

    public DateTime? updated_date { get; set; }

    public virtual course course { get; set; }

    public virtual option option { get; set; }

    public virtual question question { get; set; }

    public virtual user user { get; set; }
}