// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.Data.Entities;

public partial class user_agenda
{
    public Guid users_ag_id { get; set; }

    public Guid user_id { get; set; }

    public Guid check_inout_id { get; set; }

    public Guid lreq_id { get; set; }

    public string create_by { get; set; }

    public DateTime create_date { get; set; }

    public string update_by { get; set; }

    public DateTime update_date { get; set; }

    public virtual check_in_out check_inout { get; set; }

    public virtual leave_request lreq { get; set; }

    public virtual user user { get; set; }
}