export const customeragenda = [
  {
    id: 1,
    name: 'Phanthakit PhanthakitPatamakul',
    days: 'Monday',
    checkin: '8:58',
    checkout: '17:30',
    date: new Date(2024,11,23),
    status: 'WorkIn',
  },
  {
    id: 2,
    name: 'Phanthakit PhanthakitPatamakul',
    days: 'Tuesday',
    checkin: '8:40',
    checkout: '17:30',
    date: new Date(2024,11,24),
    status: 'WorkIn',
  },
  {
    id: 3,
    name: 'Phanthakit PhanthakitPatamakul',
    days: 'Wednesday',
    checkin: '8:40',
    checkout: '17:30',
    date: new Date(2024,11,25),
    status: 'WorkIn',
  },
  {
    id: 4,
    name: 'Phanthakit PhanthakitPatamakul',
    days: 'Thursday',
    checkin: '8:30',
    checkout: '18:00',
    date: new Date(2024,11,26),
    status: 'WorkIn',
  },
  {
    id: 5,
    name: 'Phanthakit PhanthakitPatamakul',
    days: 'Friday',
    checkin: '8:15',
    checkout: '17:30',
    date: new Date(2024,11,27),
    status: 'LeaveRequest',
  },

];
