export const Course = [
  {
    id: 1,
    title: 'angular',
    subtitle: 'คอร์สเรียนรู้พื้นฐาน การใช้ Angular',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    openDate: new Date(2024, 0, 15),
    closeDate: new Date(2024, 0, 20),
    openTime: '09:00',
    closeTime: '17:00',
    status: '',
    score: null, 
    passStatus: null, 
    chapters: [
      {
        id: 1,
        title: 'introduction',
        read: false,
        contents: [
          { id: 1, title: 'what-is-angular', body: 'Angular is a platform...', read: false },
          { id: 2, title: 'angular-features', body: 'Angular offers many features...', read: false },
        ],
      },
      {
        id: 2,
        title: 'developer-tool',
        read: false,
        contents: [
          { id: 1, title: 'setting-up', body: 'Setting up your environment...', read: false },
          { id: 2, title: 'useful-tools', body: 'Some useful tools for Angular...', read: false },
        ],
      },
    ],
    questions: [
      { id: 1, 
        question: 'What is Angular?', 
        options: [
          { id: 1, text: 'A framework' },
          { id: 2, text: 'A library' },
          { id: 3, text: 'A tool' },
          { id: 4, text: 'A database' },
        ], 
        correctAnswer: 1, 
        selectedOptionId: null,
      },
      { id: 2, 
        question: 'Which feature is NOT in Angular?', 
        options: [
          { id: 1, text: 'Directives' }, 
          { id: 2, text: 'Two-way binding' }, 
          { id: 3, text: 'Virtual DOM' }, 
          { id: 4, text: 'Dependency Injection' },
        ], 
        correctAnswer: 3, 
        selectedOptionId: null,
      },
      { id: 3, 
        question: 'What language is Angular primarily written in?', 
        options: [
          { id: 1, text: 'JavaScript' },
          { id: 2, text: 'TypeScript' },
          { id: 3, text: 'Java' },
          { id: 4, text: 'Python' },
        ],
        correctAnswer: 2, 
        selectedOptionId: null, 
      },
      { id: 4, 
        question: 'Which company developed Angular?', 
        options: [
          { id: 1, text: 'Facebook' },
          { id: 2, text: 'Google' },
          { id: 3, text: 'Microsoft' },
          { id: 4, text: 'Apple' },
        ],
        correctAnswer: 2, 
        selectedOptionId: null, 
      },
      { id: 5, 
        question: 'What is Angular CLI used for?', 
        options: [
          { id: 1, text: 'Testing apps' },
          { id: 2, text: 'Building apps' },
          { id: 3, text: 'Managing dependencies' },
          { id: 4, text: 'All of the above' },
        ],
        correctAnswer: 4, 
        selectedOptionId: null, 
      },
    ],
  },
  {
    id: 2,
    title: 'React',
    subtitle: 'คอร์สเรียนรู้พื้นฐาน การใช้ React',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    openDate: new Date(2024, 0, 25),
    closeDate: new Date(2024, 0, 30),
    openTime: '09:00',
    closeTime: '17:00',
    display: false,
    status: '',
    score: null, 
    passStatus: null, 
    chapters: [
      {
        id: 1,
        title: 'Introduction to React',
        read: false,
        contents: [
          { id: 1, title: 'React Basics', body: 'Understand the basic concepts of React, including JSX and virtual DOM.', read: false },
          { id: 2, title: 'Component-Based Architecture', body: 'React is built on reusable components that make UI design simple.', read: false },
        ],
      },
      {
        id: 2,
        title: 'React Developer Tools',
        read: false,
        contents: [
          { id: 1, title: 'Setting Up with Create React App', body: 'Learn to set up your React project quickly using Create React App.', read: false },
          { id: 2, title: 'State Management with Redux', body: 'An overview of managing state efficiently in React using Redux.', read: false },
        ],
      },
    ],
    questions: [
      { id: 1, 
        question: 'What is React?', 
        options: [ 
          { id: 1, text: 'A library' }, 
          { id: 2, text: 'A framework' }, 
          { id: 3, text: 'A programming language' }, 
          { id: 4, text: 'A tool' }
        ], 
        correctAnswer: 1, 
        selectedOptionId: null, 
      },
      { id: 2, 
        question: 'Who developed React?', 
        options: [ 
          { id: 1, text: 'Google' }, 
          { id: 2, text: 'Facebook' }, 
          { id: 3, text: 'Microsoft' }, 
          { id: 4, text: 'Apple' }
        ], 
        correctAnswer: 2, 
        selectedOptionId: null, 
      },
      { id: 3, 
        question: 'What does JSX stand for?', 
        options: [ 
          { id: 1, text: 'JavaScript XML' }, 
          { id: 2, text: 'JavaScript Xtra' }, 
          { id: 3, text: 'Java Syntax Extension' }, 
          { id: 4, text: 'None of the above' }
        ], 
        correctAnswer: 1, 
        selectedOptionId: null, 
      },
      { id: 4, 
        question: 'What is Redux used for?', 
        options: [ 
          { id: 1, text: 'UI design' }, 
          { id: 2, text: 'Routing' }, 
          { id: 3, text: 'State management' }, 
          { id: 4, text: 'Server communication' }
        ], 
        correctAnswer: 3, 
        selectedOptionId: null, 
      },
      { id: 5, 
        question: 'What is the virtual DOM?', 
        options: [ 
          { id: 1, text: 'A copy of the real DOM' }, 
          { id: 2, text: 'A database' }, 
          { id: 3, text: 'A React component' }, 
          { id: 4, text: 'A server' }
        ], 
        correctAnswer: 1, 
        selectedOptionId: null, 
      },
    ],
  },
  {
    id: 3,
    title: 'C#',
    subtitle: 'คอร์สเรียนรู้พื้นฐาน การใช้ภาษา C#',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    openDate: new Date(2024, 1, 1),
    closeDate: new Date(2024, 1, 5),
    openTime: '09:00',
    closeTime: '17:00',
    display: false,
    status: '',
    score: null, 
    passStatus: null, 
    chapters: [
      {
        id: 1,
        title: 'Introduction to C#',
        read: false,
        contents: [
          { id: 1, title: 'C# Basics', body: 'Learn the basic syntax and structure of C# programming language.', read: false },
          { id: 2, title: 'Variables and Data Types', body: 'Understand how to declare variables and use different data types in C#.', read: false },
        ],
      },
      {
        id: 2,
        title: 'Advanced C# Concepts',
        read: false,
        contents: [
          { id: 1, title: 'Object-Oriented Programming', body: 'Dive into OOP concepts like classes, inheritance, and polymorphism in C#.', read: false },
          { id: 2, title: 'Asynchronous Programming', body: 'Learn how to use async and await for asynchronous programming in C#.', read: false },
        ],
      },
    ],
    questions: [
      { id: 1, 
        question: 'What is C#?', 
        options: [ 
          { id: 1, text: 'A scripting language' }, 
          { id: 2, text: 'A programming language' }, 
          { id: 3, text: 'A markup language' }, 
          { id: 4, text: 'A database tool' }
        ], 
        correctAnswer: 2, 
        selectedOptionId: null, 
      },
      { id: 2, 
        question: 'Which platform is C# primarily used for?', 
        options: [ 
          { id: 1, text: 'Android' }, 
          { id: 2, text: 'Windows' }, 
          { id: 3, text: 'MacOS' }, 
          { id: 4, text: 'Linux' }
        ], 
        correctAnswer: 2, 
        selectedOptionId: null, 
      },
      { id: 3, 
        question: 'What does OOP stand for?', 
        options: [ 
          { id: 1, text: 'Object-Oriented Programming' }, 
          { id: 2, text: 'Open Operating Platform' }, 
          { id: 3, text: 'Optimized Output Processing' }, 
          { id: 4, text: 'Object-Oriented Performance' }
        ], 
        correctAnswer: 1, 
        selectedOptionId: null, 
      },
      { id: 4, 
        question: 'Which keyword is used to define a class in C#?', 
        options: [ 
          { id: 1, text: 'class' }, 
          { id: 2, text: 'object' }, 
          { id: 3, text: 'define' }, 
          { id: 4, text: 'structure' }
        ], 
        correctAnswer: 1, 
        selectedOptionId: null, 
      },
      { id: 5, 
        question: 'What is the purpose of the async keyword in C#?', 
        options: [ 
          { id: 1, text: 'To define variables' }, 
          { id: 2, text: 'To handle errors' }, 
          { id: 3, text: 'To support asynchronous programming' }, 
          { id: 4, text: 'To improve performance' }
        ], 
        correctAnswer: 3, 
        selectedOptionId: null, 
      },
    ],
  },
  {
    id: 4,
    title: 'Java',
    subtitle: 'คอร์สเรียนรู้พื้นฐาน การใช้ภาษา Java',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    openDate: new Date(2024, 2, 10),
    closeDate: new Date(2024, 2, 15),
    openTime: '10:00',
    closeTime: '16:00',
    display: false,
    status: '',
    score: null, 
    passStatus: null,
    chapters: [
      {
        id: 1,
        title: 'Introduction to Java',
        read: false,
        contents: [
          { id: 1, title: 'Java Basics', body: 'Learn the syntax and basic concepts of Java programming.', read: false },
          { id: 2, title: 'Object-Oriented Programming', body: 'Understand OOP concepts in Java, including classes and inheritance.', read: false },
        ],
      },
      {
        id: 2,
        title: 'Java Developer Tools',
        read: false,
        contents: [
          { id: 1, title: 'Setting Up Your Environment', body: 'Learn to set up the Java development environment.', read: false },
          { id: 2, title: 'Using IDEs for Java', body: 'Explore the most popular IDEs for Java development, such as IntelliJ and Eclipse.', read: false },
        ],
      },
    ],
    questions: [
      { id: 1, 
        question: 'What is Java?', 
        options: [ 
          { id: 1, text: 'A database' }, 
          { id: 2, text: 'A programming language' }, 
          { id: 3, text: 'A text editor' }, 
          { id: 4, text: 'A web browser' }
        ], 
        correctAnswer: 2, 
        selectedOptionId: null, 
      },
      { id: 2, 
        question: 'Who developed Java?', 
        options: [ 
          { id: 1, text: 'Microsoft' }, 
          { id: 2, text: 'Google' }, 
          { id: 3, text: 'Sun Microsystems' }, 
          { id: 4, text: 'Apple' }
        ], 
        correctAnswer: 3, 
        selectedOptionId: null, 
      },
      { id: 3, 
        question: 'What does JVM stand for?', 
        options: [ 
          { id: 1, text: 'Java Visual Machine' }, 
          { id: 2, text: 'Java Virtual Machine' }, 
          { id: 3, text: 'Java Variable Management' }, 
          { id: 4, text: 'Java Version Manager' }
        ], 
        correctAnswer: 2, 
        selectedOptionId: null, 
      },
      { id: 4, 
        question: 'Which method is the entry point of a Java program?', 
        options: [ 
          { id: 1, text: 'main()' }, 
          { id: 2, text: 'start()' }, 
          { id: 3, text: 'entry()' }, 
          { id: 4, text: 'execute()' }
        ], 
        correctAnswer: 1, 
        selectedOptionId: null, 
      },
      { id: 5, 
        question: 'Which keyword is used to inherit a class in Java?', 
        options: [ 
          { id: 1, text: 'extends' }, 
          { id: 2, text: 'inherits' }, 
          { id: 3, text: 'super' }, 
          { id: 4, text: 'this' }
        ], 
        correctAnswer: 1, 
        selectedOptionId: null, 
      },
    ],
  },
];
