// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Status_ColorAPI.Entities;

public partial class StatusColor
{
    public long StatusId { get; set; }

    public string StatusType { get; set; }

    public string StatusCode { get; set; }

    public string StatusName { get; set; }

    public bool Active { get; set; }
}