// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.App.Entities;

public partial class CheckInOut
{
    public Guid CheckInoutId { get; set; }

    public Guid UserId { get; set; }

    public DateTime? CheckIn { get; set; }

    public DateTime? CheckOut { get; set; }

    public DateTime CheckDates { get; set; }

    public string CreateBy { get; set; }

    public DateTime CreateDate { get; set; }

    public string UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<UserAgendum> UserAgenda { get; set; } = new List<UserAgendum>();
}