// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Ems.App.Entities;

public partial class EmsContext : DbContext
{
    public EmsContext(DbContextOptions<EmsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Chapter> Chapters { get; set; }

    public virtual DbSet<ChapterContent> ChapterContents { get; set; }

    public virtual DbSet<CheckInOut> CheckInOuts { get; set; }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<LeaveRequest> LeaveRequests { get; set; }

    public virtual DbSet<Option> Options { get; set; }

    public virtual DbSet<Position> Positions { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    public virtual DbSet<Registration> Registrations { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserAgendum> UserAgenda { get; set; }

    public virtual DbSet<UserQuestion> UserQuestions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresEnum("lang", new[] { "th", "en" })
            .HasPostgresExtension("uuid-ossp");

        modelBuilder.Entity<Chapter>(entity =>
        {
            entity.HasKey(e => e.ChapterId).HasName("chapter_pkey");

            entity.ToTable("chapter", "ems");

            entity.Property(e => e.ChapterId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("chapter_id");
            entity.Property(e => e.ChapterTitle)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("chapter_title");
            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_date");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_date");

            entity.HasOne(d => d.Course).WithMany(p => p.Chapters)
                .HasForeignKey(d => d.CourseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_course");
        });

        modelBuilder.Entity<ChapterContent>(entity =>
        {
            entity.HasKey(e => e.ContentId).HasName("chapter_content_pkey");

            entity.ToTable("chapter_content", "ems");

            entity.Property(e => e.ContentId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("content_id");
            entity.Property(e => e.ChapterId).HasColumnName("chapter_id");
            entity.Property(e => e.ContentBody)
                .IsRequired()
                .HasColumnName("content_body");
            entity.Property(e => e.ContentTitle)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("content_title");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_date");
            entity.Property(e => e.Read)
                .HasDefaultValue(false)
                .HasColumnName("read");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_date");

            entity.HasOne(d => d.Chapter).WithMany(p => p.ChapterContents)
                .HasForeignKey(d => d.ChapterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_chapter");
        });

        modelBuilder.Entity<CheckInOut>(entity =>
        {
            entity.HasKey(e => e.CheckInoutId).HasName("check_in_out_pkey");

            entity.ToTable("check_in_out", "ems");

            entity.Property(e => e.CheckInoutId)
                .ValueGeneratedNever()
                .HasColumnName("check_inout_id");
            entity.Property(e => e.CheckDates)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("check_dates");
            entity.Property(e => e.CheckIn)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("check_in");
            entity.Property(e => e.CheckOut)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("check_out");
            entity.Property(e => e.CreateBy)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("create_by");
            entity.Property(e => e.CreateDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("create_date");
            entity.Property(e => e.UpdateBy)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("update_by");
            entity.Property(e => e.UpdateDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("update_date");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.CheckInOuts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("check_in_out_user_id_fkey");
        });

        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.CourseId).HasName("course_pkey");

            entity.ToTable("course", "ems");

            entity.Property(e => e.CourseId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("course_id");
            entity.Property(e => e.CourseName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("course_name");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_date");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.EndDate).HasColumnName("end_date");
            entity.Property(e => e.EndTime).HasColumnName("end_time");
            entity.Property(e => e.StartDate).HasColumnName("start_date");
            entity.Property(e => e.StartTime).HasColumnName("start_time");
            entity.Property(e => e.Subtitle)
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnName("subtitle");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<LeaveRequest>(entity =>
        {
            entity.HasKey(e => e.LreqId).HasName("leave_request_pkey");

            entity.ToTable("leave_request", "ems");

            entity.Property(e => e.LreqId)
                .ValueGeneratedNever()
                .HasColumnName("lreq_id");
            entity.Property(e => e.CreateBy)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("create_by");
            entity.Property(e => e.CreateDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("create_date");
            entity.Property(e => e.LreqDate).HasColumnName("lreq_date");
            entity.Property(e => e.LreqDescription)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("lreq_description");
            entity.Property(e => e.UpdateBy)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("update_by");
            entity.Property(e => e.UpdateDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("update_date");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.LeaveRequests)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("leave_request_user_id_fkey");
        });

        modelBuilder.Entity<Option>(entity =>
        {
            entity.HasKey(e => e.OptionId).HasName("option_pkey");

            entity.ToTable("option", "ems");

            entity.Property(e => e.OptionId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("option_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_date");
            entity.Property(e => e.OptionText)
                .IsRequired()
                .HasColumnName("option_text");
            entity.Property(e => e.QuestionId).HasColumnName("question_id");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_date");

            entity.HasOne(d => d.Question).WithMany(p => p.Options)
                .HasForeignKey(d => d.QuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_question");
        });

        modelBuilder.Entity<Position>(entity =>
        {
            entity.HasKey(e => e.PositionId).HasName("positions_pkey");

            entity.ToTable("position", "ems");

            entity.Property(e => e.PositionId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("position_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_date");
            entity.Property(e => e.PositionName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("position_name");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasKey(e => e.QuestionId).HasName("question_pkey");

            entity.ToTable("question", "ems");

            entity.Property(e => e.QuestionId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("question_id");
            entity.Property(e => e.CorrectAnswer).HasColumnName("correct_answer");
            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_date");
            entity.Property(e => e.QuestionText)
                .IsRequired()
                .HasColumnName("question_text");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_date");

            entity.HasOne(d => d.Course).WithMany(p => p.Questions)
                .HasForeignKey(d => d.CourseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_course");
        });

        modelBuilder.Entity<Registration>(entity =>
        {
            entity.HasKey(e => e.RegistrationId).HasName("registration_pkey");

            entity.ToTable("registration", "ems");

            entity.Property(e => e.RegistrationId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("registration_id");
            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_date");
            entity.Property(e => e.PassStatus).HasColumnName("pass_status");
            entity.Property(e => e.Score).HasColumnName("score");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_date");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Course).WithMany(p => p.Registrations)
                .HasForeignKey(d => d.CourseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_course");

            entity.HasOne(d => d.Status).WithMany(p => p.Registrations)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_status");

            entity.HasOne(d => d.User).WithMany(p => p.Registrations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_user");
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.HasKey(e => e.StatusId).HasName("status_pkey");

            entity.ToTable("status", "ems");

            entity.HasIndex(e => e.StatusName, "status_status_name_key").IsUnique();

            entity.Property(e => e.StatusId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("status_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_date");
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("status_name");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_date");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("user_pkey");

            entity.ToTable("user", "ems");

            entity.HasIndex(e => e.Email, "user_email_key").IsUnique();

            entity.Property(e => e.UserId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("user_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_date");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("first_name");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("last_name");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("password");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("phone");
            entity.Property(e => e.PositionId).HasColumnName("position_id");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_date");

            entity.HasOne(d => d.Position).WithMany(p => p.Users)
                .HasForeignKey(d => d.PositionId)
                .HasConstraintName("fk_user_position");
        });

        modelBuilder.Entity<UserAgendum>(entity =>
        {
            entity.HasKey(e => e.UsersAgId).HasName("user_agenda_pkey");

            entity.ToTable("user_agenda", "ems");

            entity.Property(e => e.UsersAgId)
                .ValueGeneratedNever()
                .HasColumnName("users_ag_id");
            entity.Property(e => e.CheckInoutId).HasColumnName("check_inout_id");
            entity.Property(e => e.CreateBy)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("create_by");
            entity.Property(e => e.CreateDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("create_date");
            entity.Property(e => e.LreqId).HasColumnName("lreq_id");
            entity.Property(e => e.UpdateBy)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("update_by");
            entity.Property(e => e.UpdateDate)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("update_date");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.CheckInout).WithMany(p => p.UserAgenda)
                .HasForeignKey(d => d.CheckInoutId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("user_agenda_check_inout_id_fkey");

            entity.HasOne(d => d.Lreq).WithMany(p => p.UserAgenda)
                .HasForeignKey(d => d.LreqId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("user_agenda_lreq_id_fkey");

            entity.HasOne(d => d.User).WithMany(p => p.UserAgenda)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("user_agenda_user_id_fkey");
        });

        modelBuilder.Entity<UserQuestion>(entity =>
        {
            entity.HasKey(e => e.UserQuestionId).HasName("user_question_pkey");

            entity.ToTable("user_question", "ems");

            entity.Property(e => e.UserQuestionId)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("user_question_id");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_date");
            entity.Property(e => e.QuestionId).HasColumnName("question_id");
            entity.Property(e => e.SelectedOptionId).HasColumnName("selected_option_id");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");
            entity.Property(e => e.UpdatedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_date");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Question).WithMany(p => p.UserQuestions)
                .HasForeignKey(d => d.QuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_question");

            entity.HasOne(d => d.SelectedOption).WithMany(p => p.UserQuestions)
                .HasForeignKey(d => d.SelectedOptionId)
                .HasConstraintName("fk_option");

            entity.HasOne(d => d.User).WithMany(p => p.UserQuestions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_user");
        });
        modelBuilder.HasSequence("db_district_district_code_seq");
        modelBuilder.HasSequence("db_district_district_id_seq");
        modelBuilder.HasSequence("db_postal_code_postal_code_id_seq").HasMax(2147483647L);
        modelBuilder.HasSequence("db_province_province_code_seq");
        modelBuilder.HasSequence("db_province_province_id_seq");
        modelBuilder.HasSequence("db_subdistrict_subdistrict_code_seq");
        modelBuilder.HasSequence("db_subdistrict_subdistrict_id_seq");
        modelBuilder.HasSequence("history_id_seq");
        modelBuilder.HasSequence("pm_backlog_backlog_id_seq");
        modelBuilder.HasSequence("pm_customer_customer_id_seq");
        modelBuilder.HasSequence("pm_project_member_project_member_id_seq");
        modelBuilder.HasSequence("pm_project_project_id_seq");
        modelBuilder.HasSequence("pm_roadmap_roadmap_id_seq");
        modelBuilder.HasSequence("seq");
        modelBuilder.HasSequence("su_user_user_id_seq");
        modelBuilder.HasSequence("tw_customer_customer_id_seq");
        modelBuilder.HasSequence("tw_project_project_id_seq");
        modelBuilder.HasSequence("tw_task_work_task_work_id_seq");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}