// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.App.Entities;

public partial class LeaveRequest
{
    public Guid LreqId { get; set; }

    public Guid UserId { get; set; }

    public DateOnly LreqDate { get; set; }

    public string LreqDescription { get; set; }

    public string CreateBy { get; set; }

    public DateTime CreateDate { get; set; }

    public string UpdateBy { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<UserAgendum> UserAgenda { get; set; } = new List<UserAgendum>();
}