// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.App.Entities;

public partial class Option
{
    public Guid OptionId { get; set; }

    public Guid QuestionId { get; set; }

    public string OptionText { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual Question Question { get; set; }

    public virtual ICollection<UserQuestion> UserQuestions { get; set; } = new List<UserQuestion>();
}