// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.App.Entities;

public partial class Question
{
    public Guid QuestionId { get; set; }

    public Guid CourseId { get; set; }

    public string QuestionText { get; set; }

    public int CorrectAnswer { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<Option> Options { get; set; } = new List<Option>();

    public virtual ICollection<UserQuestion> UserQuestions { get; set; } = new List<UserQuestion>();
}