// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.App.Entities;

public partial class Quiz
{
    public Guid QuizId { get; set; }

    public Guid CourseId { get; set; }

    public string Question { get; set; }

    public string Options { get; set; }

    public int CorrectAnswer { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<UserQuiz> UserQuizzes { get; set; } = new List<UserQuiz>();
}