// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.App.Entities;

public partial class Registration
{
    public Guid RegistrationId { get; set; }

    public Guid UserId { get; set; }

    public Guid CourseId { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public Guid StatusId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual Course Course { get; set; }

    public virtual Status Status { get; set; }

    public virtual User User { get; set; }
}