// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.App.Entities;

public partial class UserQuiz
{
    public Guid UserQuizId { get; set; }

    public Guid UserId { get; set; }

    public Guid QuizId { get; set; }

    public int? Score { get; set; }

    public bool? Passed { get; set; }

    public DateTime? AttemptDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual Quiz Quiz { get; set; }

    public virtual User User { get; set; }
}