// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ems.App.Entities;

public partial class UserAgendum
{
    public Guid UsersAgId { get; set; }

    public Guid UserId { get; set; }

    public Guid CheckInoutId { get; set; }

    public Guid LreqId { get; set; }

    public string CreateBy { get; set; }

    public DateTime CreateDate { get; set; }

    public string UpdateBy { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual CheckInOut CheckInout { get; set; }

    public virtual LeaveRequest Lreq { get; set; }

    public virtual User User { get; set; }
}