// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Status_ColorAPI.Models;

#nullable disable

namespace Status_ColorAPI.Migrations
{
    [DbContext(typeof(StatusColorContext))]
    [Migration("20241204095400_StatusColor")]
    partial class StatusColor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Status_ColorAPI.Models.StatusColor", b =>
                {
                    b.Property<long>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigserial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StatusId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bool");

                    b.Property<string>("StatusCode")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StatusName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StatusType")
                        .HasColumnType("varchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("StatusColors");
                });
#pragma warning restore 612, 618
        }
    }
}
